name: Code Analyzing
run-name: Analyzing the code written by ${{ github.actor }} 🚀

on: [ push ]

jobs:
    PHPStan:
        runs-on: ubuntu-latest
        container:
            image: ubuntu:latest

        strategy:
            fail-fast: false
            matrix:
                laravel: [ '12', '13' ]

        name: PHPStan / Laravel ${{ matrix.laravel }}

        steps:
            -   name: Checkout code (git)
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    tools: composer

            -   name: Install dependencies with composer
                run: >
                    composer update --with-all-dependencies --no-progress
                    --with "laravel/framework:^${{ matrix.laravel }}.0"

            -   name: Run PHPStan
                run: ./vendor/bin/phpstan analyze --memory-limit 2G
